### ISSUE TITLE
Is it okay to add eslint for this project ?

### ISSUE THREAD

**Issue by gengjiawen** [Molunerfinn/vue-koa-demo#11]
RT

**Comment by Molunerfinn** [comment]
I am waiting for [this](https://github.com/vuejs/eslint-plugin-vue-libs) HAHA

**Comment by gengjiawen** [comment]
But the link is for vue internal development. And we may also need for server eslint config.

**Comment by Molunerfinn** [comment]
I find that your pr is ruled by eslint. Actually I haven't used eslint in my project. It's cool to add it~

**Comment by gengjiawen** [comment]
I only apply it to server, but I can add it to frontend too if you are okay with it.

**Comment by Molunerfinn** [comment]
I’m okay~ In fact, I remember that `vue-cli` have the eslint config opiton, but I didn't choose it. As this project I created, I didn't learn about eslint HAHA

**Comment by Molunerfinn** [comment]
Eslint done~
