### ISSUE TITLE
你好。访问接口504错误是啥原因呢？

### ISSUE THREAD

**Issue by cgygd** [Molunerfinn/vue-koa-demo#15]
npm run dev跑起来之后，
登陆接口报错

[HPM] Error occurred while trying to proxy request /auth/user from localhost:8080 to http://localhost:8889 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by Molunerfinn** [comment]
api接口请用`npm run server`跑起来。README已经更新~

**Comment by cgygd** [comment]
好的。谢谢，可以了

**Comment by Nebulazheng** [comment]
请问我也是504错误 ,是修改.env.js吗？
我的是：
`import * as dotenv from 'dotenv'
let path = process.env.NODE_ENV === 'test' ? '.env.test' : '.env'
dotenv.config({path, silent: true})`

**Comment by Molunerfinn** [comment]
@Nebulazheng  上面不是说了：api接口请用npm run server跑起来么...

**Comment by Molunerfinn** [comment]
Node默认不支持ES6的import语法，需要用babel转义一下。

**Comment by Nebulazheng** [comment]
> @Nebulazheng 上面不是说了：api接口请用npm run server跑起来么......

可以运行了谢谢

**Comment by Nebulazheng** [comment]
请问 我启动项目可以正常运行登录了，但我尝试用postman去post登录接口，会返回用户不存在，console models/user.js中getUserByName(name)函数的name是undefind,在启动vue页面登录时打印出来正常
