### ISSUE TITLE
前端直接解析token是不是太危险？

### ISSUE THREAD

**Issue by WelcomeToEarth** [Molunerfinn/vue-koa-demo#16]
RT

**Comment by Molunerfinn** [comment]
博客中已经指出，是不安全，不过只是个DEMO，所以没有考虑太多。另外如果用`jwt_decode`解析token，是不会暴露key的

**Comment by gengjiawen** [comment]
Token解析严格来说应该放在后端的, 现在使用的类库应该能支持这一点吧。

**Comment by Molunerfinn** [comment]
@gengjiawen JWT的payload可以存放非关键信息，由于本身也只是base64编码，所以在前端解析是没关系的。只要不暴露关键信息即可。有的时候需要在payload里放一些索引信息比如id来进行身份鉴别
