### ISSUE TITLE
ctx.request.body获取不到post请求的参数

### ISSUE THREAD

**Issue by Reckfu1** [Molunerfinn/vue-koa-demo#18]
ctx.request.body获取不到post请求的参数

**Comment by Molunerfinn** [comment]
请详细说明一下，是否有报错，自己手动console`ctx.request`的话输出什么？Nodejs和koa的版本是否匹配？

**Comment by Reckfu1** [comment]
无报错，只是返回空对象，在koa文档找到解决方法了，使用ctx.request.query可以返回参数信息

**Comment by Reckfu1** [comment]
@Molunerfinn 请问可否留下qq号 我有个问题不太明白想请教一下 谢谢
