### ISSUE TITLE
你起了两个服务么？

### ISSUE THREAD

**Issue by TaurusWood** [Molunerfinn/vue-koa-demo#19]
我有点没看懂，
vue-cli里面已经用express起了一个服务，然后你单独用koa又启动了一个服务，是这样么？
我这里有两个问题：
1. koa的端口你写的是8989，但是vue-cli的默认端口是3000吧，这个会冲突么？
2. 你是如何在8989端口监听到webpack所编译的文件的呢？就像在vue-cli的`dev-server.js`中有`app.use(devMiddleware)`来做这一步。

**Comment by Molunerfinn** [comment]
开发模式下是起了两个端口的。1个是给webpack输出的express，1个是给koa的。
本项目中vue-cli起的服务是8080端口，具体在`config/index.js`里的dev处口以看到。这个可以自定义，找个不冲突的端口就行。
8989端口只是koa的端口。。注意看`config/index.js`里的proxyTable，做了一次代理，否则要跨域
