### ISSUE TITLE
为什么要将所有的路由信息直接放在controllers里面呢

### ISSUE THREAD

**Issue by cristicVictory** [Molunerfinn/vue-koa-demo#2]
为什么要将所有的路由信息直接放在controllers里面呢，如果是多个controllers的情况下，那不是有问题了吗？而且这样分层的情况不是很好吧

**Comment by Molunerfinn** [comment]
嗯，如果有多个controllers确实会有点问题。。我抽空将结构优化一下~感谢提醒:)

**Comment by Molunerfinn** [comment]
已修复，感谢提醒~:）
