### ISSUE TITLE
The code  don't encrypt the password in the client  ?

### ISSUE THREAD

**Issue by AChaoZJU** [Molunerfinn/vue-koa-demo#21]
By looking up the network, I have found that, the code  don't encrypt the password in the client . 
<br>
It's confusing for me to understand what you say in your tutorial.

> 用户在登录页输入账号密码，将账号密码（密码进行md5加密）发送请求给后端

**Comment by Molunerfinn** [comment]
See this [pr](https://github.com/Molunerfinn/vue-koa-demo/pull/3). The tutorial is written with the first version of the code. So may be there are some conflicts.
