### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by outOFFspace** [Molunerfinn/vue-koa-demo#23]
Any plans about SSR?

**Comment by Molunerfinn** [comment]
I think I can make it on the ssr branch in this month : )

**Comment by Molunerfinn** [comment]
Partly finished in the [ssr](https://github.com/Molunerfinn/vue-koa-demo/tree/ssr) branch. Use `npm run server` or `yarn server` then it works. 
However, it still has some problems:
1. can't hot reload
2. can't refresh the page using F5
I will try my best to solve those problems in these days.
: )

**Comment by Molunerfinn** [comment]
Update: 2017/12/01
In dev mode,  I have solved the two problems above:
1. in dev mode, now you can hot reload
2. in dev mode, now you can refresh page using F5

I haven't do the production mode, but I will do it ASAP.
 : )
