### ISSUE TITLE
Vue.prototype.$http = axios 报错

### ISSUE THREAD

**Issue by yancongcong1** [Molunerfinn/vue-koa-demo#26]
您好：
        我在编写测试用例的时候这段报错，提示$http只有getter方法，请问您有遇到过这个问题吗？
        TypeError: Cannot set property $http of #<Vue$3> which has only a getter

**Comment by Molunerfinn** [comment]
并没有。。是我本例里的测试用例没有跑通么？

**Comment by yancongcong1** [comment]
不是的，这是我借鉴您的用例在自己项目中使用这种方法的时候出现的这种错误，所以想找您咨询一下

**Comment by Molunerfinn** [comment]
额抱歉我这边无法复现这个问题。。issue先关闭了。如果你解决了问题或者你依然无法解决问题可以给个github仓库地址让其他人一起看看~
