### ISSUE TITLE
新年好，楼主请帮忙，这是es6的转义导致的吗？

### ISSUE THREAD

**Issue by jonnzer** [Molunerfinn/vue-koa-demo#28]
![image](https://user-images.githubusercontent.com/21023707/36321809-15ab426a-1386-11e8-9f26-47256d5e1c46.png)

**Comment by Molunerfinn** [comment]
看报错就知道不是啊...
你把我对.env文件的注释也抄进去了当然就错了。。。
正确的是：
```bash
DB_USER=XXXX
DB_PASSWORD=YYYY 
PORT=8888
```
这样就好了，不需要井号那堆注释。我已经修改了readme，防止再误导后人。新年快乐。

**Comment by jonnzer** [comment]
![image](https://user-images.githubusercontent.com/21023707/36342443-9ae3bf6c-1439-11e8-9c69-6e4fe7701fd5.png)
楼主，这种属于什么格式的密码呢？
