### ISSUE TITLE
ssr分支->reademe.md 对.env配置说明有误

### ISSUE THREAD

**Issue by chenzhongchen27** [Molunerfinn/vue-koa-demo#30]
如：
![image](https://user-images.githubusercontent.com/16606198/38767570-6ed66cc2-4016-11e8-9da2-11eb46d7196b.png)

下面这种是错误的，会被解析为 `process.env.DB_USER="XXXX # your database username"`
```
DB_USER=XXXX # your database username
```

下面这种是正确的，才会被正确解析为 `process.env.DB_USER="XXXX"`
```
## your database username
DB_USER=XXXX 
```

**Comment by Molunerfinn** [comment]
这个本来是个注释。不过没想到大家都有所误解。现在已经改了，感谢指出~
