### ISSUE TITLE
代理端口号出错

### ISSUE THREAD

**Issue by liuyong** [Molunerfinn/vue-koa-demo#31]
➜  vue-koa-demo git:(master) ✗ npm run dev && npm run server

> vue-koa-demo@1.0.0 dev /Users/XNW/Documents/Vuejs_workspace/vue-koa-demo
> node build/dev-server.js

[HPM] Proxy created: /auth  ->  http://localhost:8889
[HPM] Proxy created: /api  ->  http://localhost:8889
> Starting dev server...

 DONE  Compiled successfully in 5084ms                                  17:02:41

> Listening at http://localhost:8080

[HPM] Error occurred while trying to proxy request /auth/user from localhost:8080 to http://localhost:8889 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by Molunerfinn** [comment]
参考：https://github.com/Molunerfinn/vue-koa-demo/issues/15
和https://github.com/Molunerfinn/vue-koa-demo/issues/8

1. 请分开跑前端和后端的命令。
2. 请注意你的env里的port 8889是否被其他进程占用。

**Comment by liuyong** [comment]
➜  vue-koa-demo git:(master) ✗ npm run server

> vue-koa-demo@1.0.0 server /Users/XNW/Documents/Vuejs_workspace/vue-koa-demo
> nodemon -w app.js -w server server-entry.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app.js /Users/XNW/Documents/Vuejs_workspace/vue-koa-demo/server/**/*
[nodemon] starting `node server-entry.js`
Koa is listening in undefined
rs
[nodemon] starting `node server-entry.js`
Koa is listening in undefined

试过换端口，losf查端口占用，重启等都一样是报这个错，单跑npm run server 提示 Koa is listening in undefined

**Comment by Molunerfinn** [comment]
请问你的`.env`文件长啥样？

**Comment by liuyong** [comment]
文件 dev.env 内容是：
DB_USER=root
DB_PASSWORD=mysqlpwd
PORT=8887

**Comment by Molunerfinn** [comment]
。。。并不能叫做`dev.env`必须叫做`.env`。文件名改一下吧。然后把PORT改成8889就行了。

**Comment by liuyong** [comment]
嗯，正常跑起来了，感谢~~
