### ISSUE TITLE
运行时遇到一些问题

### ISSUE THREAD

**Issue by MostW** [Molunerfinn/vue-koa-demo#34]
[HPM] Error occurred while trying to proxy request /auth/user from localhost:8080 to http://localhost:8889 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by Molunerfinn** [comment]
不要重复开issue啊。我已经回复你了：
请查看这个issue：https://github.com/Molunerfinn/vue-koa-demo/issues/31

**Comment by MostW** [comment]
不好意思，刚才没看到邮件，现在解决了
，谢谢
--------------原始邮件--------------
发件人："PiEgg "<notifications@github.com>;
发送时间：2018年5月30日(星期三) 下午3:45
收件人："Molunerfinn/vue-koa-demo" <vue-koa-demo@noreply.github.com>;
抄送："MostW "<2014150113@email.szu.edu.cn>;"Author "<author@noreply.github.com>;
主题：Re: [Molunerfinn/vue-koa-demo] 运行时遇到一些问题 (#34)
-----------------------------------

不要重复开issue啊。我已经回复你了：
 请查看这个issue：#31
