### ISSUE TITLE
作者大大，方便交流下nginx配置吗？

### ISSUE THREAD

**Issue by jonnzer** [Molunerfinn/vue-koa-demo#35]
您好，我已经看过您的文章，但是我疑惑的是server代码是不是要放在服务器里，然后是怎么启动的，每次都要手动的node server_entry.js吗，盼回复，感谢您！

**Comment by Molunerfinn** [comment]
生产环境下应该要先build，然后再用pm2启动。命令是`npm run start:pm2`，代码如下：
https://github.com/Molunerfinn/vue-koa-demo/blob/master/package.json#L15

nginx方面的配置大概是这样（只给关键部分）：

```nginx
http {
  upstream nodeServer {
    server 127.0.0.1:8888;
  }
  server {
    listen: 80;
    server_name: nodeServer;
    location / {
      proxy_pass http://nodeServer;
      proxy_redirect off;
    }
  }
}

你可以选择在服务端构建也可以选择在本地构建完把dist目录上传。

代码的话，如果是生产环境，主要就是这几个文件/目录：

- server-entry.js
- app.js
- env.js
- .env
- dist/
- server/

当然不推荐单独把关键文件目录拿出来。推荐是可以把代码放服务端然后在服务端构建。

**Comment by jonnzer** [comment]
您看看这样的配置是可以的吗？
user root;
worker_processes auto;
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    include /etc/nginx/conf.d/*.conf;
 # root         /var/www/server_house;
 # root         /var/www/groceryHouse;这是项目的根目录 
     upstream nodeServer {
            server 127.0.0.1:3000;
    }
    server {
        listen      80;
        server_name : nodeServer;
        include /etc/nginx/default.d/*.conf;
        location / {
             proxy_pass http://nodeServer;
            proxy_redirect off;
        }
    }
}
我的qq是991656886，可能需要您的帮助才行。自己调不通。

**Comment by jonnzer** [comment]
user root;
worker_processes auto;
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    include /etc/nginx/conf.d/*.conf;
 注释  root         /var/www/server_house;
 注释 root         /var/www/groceryHouse;这是项目的根目录 
     upstream nodeServer {
            server 127.0.0.1:3000;
    }
    server {
        listen      80;
        server_name : nodeServer;
        include /etc/nginx/default.d/*.conf;
        location / {
             proxy_pass http://nodeServer;
            proxy_redirect off;
        }
    }
}
