### ISSUE TITLE
为什么不能使用import

### ISSUE THREAD

**Issue by ibubbo** [Molunerfinn/vue-koa-demo#38]
我只要是写了`import`或者`export default`等es6的东西，就会报以下错误，怎么破。。
![image](https://user-images.githubusercontent.com/32586819/48673953-1bd4b200-eb82-11e8-82b8-c3e3ec17141b.png)

**Comment by Molunerfinn** [comment]
node端原生其实不支持import export语法的。需要用babel转义。
你可以看看入口文件：https://github.com/Molunerfinn/vue-koa-demo/blob/master/server-entry.js
