### ISSUE TITLE
想搭建远程调试，一直不成功

### ISSUE THREAD

**Issue by sonygod** [Molunerfinn/vue-koa-demo#40]
git clone后已经成功运行。

想搭建远程调试，一直不成功

server和前端已经在远程服务器运行起来，怎么远程调试？

参考N多文章没有成功，例子都是介绍非常简单的node普通的单例，好像这个demo启动参数有点多

远程服务器 启动调试配置

   ` $   node --inspect ` 

或者

   `$ node --inspect-brk app.js`

可以运行，但链接不上。一直timeout.

   ` $   node --inspect  app.js`

直接报错，
  
  启动配置

  {
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      
      {
        "type": "node",
        "request": "attach",
        "name": "Attach to Remote",
        "address": "192.168.65.131",
        "port": 9229,
        "localRoot": "${workspaceFolder}",
        "remoteRoot": "/home/test/vue-koa-demo/"
      }
    ]
    }
 
哪里错了？
服务器：ubuntu 18.

**Comment by Molunerfinn** [comment]
你远程服务器的IP是192.168.65.131么？这不是本地路由器分配的一个IP地址么

**Comment by Molunerfinn** [comment]
而且我也没搭建过远程调试，没法给出解答

**Comment by sonygod** [comment]
是win7下开发，虚拟机ubuntu 运行vue-koa-demo,  成功后放上腾讯云

**Comment by Molunerfinn** [comment]
嗯，不过我没有相关经验能帮上忙..我一般是直接上开发机写代码和调试

**Comment by sonygod** [comment]
最后在这里找到不太优雅的答案，总比没有好，

[debugger](https://stackoverflow.com/questions/6727370/using-chrome-javascript-debugger-how-to-break-on-page-loading-events)

远程服务器 

$ node --inspect=192.168.65.131:9229 server-entry.js

然后在你需要的debug的地方代码里面输入 debugger， 非常丑陋，但可以用，不能随意加断点。

**Comment by sonygod** [comment]
补充一下，更新google chrome最新版73 ，不用加debugger标志了，原理是我chrome版本过旧的问题

**Comment by Molunerfinn** [comment]
@sonygod 感谢
