### ISSUE TITLE
[单元测试] vue-router的跳转怎么验证？

### ISSUE THREAD

**Issue by blackcloud2333** [Molunerfinn/vue-koa-demo#42]
【需求】：期望能够覆盖到页面当中的vue-touter的跳转代码
  【现状】：在login.spec.js文件当中没有发现关于vue-router的代码
   【问题】：1 如何验证vue-router有效？
                      2 如何验vue-router执行的正确性？
  【解决思路】：1 验证vue-router的push方法是否被调用了
                            其他的就没有解决思路了，但是不能解决【问题】1，2当中的疑问。
求教大佬。解决思路，能补充点demo最好不过

**Comment by Molunerfinn** [comment]
我自己没有写过这方面的测试，不过官方有给出一些思路：https://vue-test-utils.vuejs.org/guides/using-with-vue-router.html
验证push是否被调用了，可以判断点击之后的`$route.path`是否为预期的path。只是一个思路供参考

**Comment by blackcloud2333** [comment]
get,会思考有没有其他的解决方案，如果没有，暂时就只能这样了。
感谢大佬！
