### ISSUE TITLE
数据库连接报错

### ISSUE THREAD

**Issue by Essentric** [Molunerfinn/vue-koa-demo#43]
大神,我参照你的写法,出现了如下的数据连接错误,不知道你是否有遇到过
![image](https://user-images.githubusercontent.com/32890926/55677329-1d77fa00-5918-11e9-86bf-e59526d3a7ff.png)

**Comment by Molunerfinn** [comment]
没有，你mysql的3306端口开了么

**Comment by Essentric** [comment]
额..我解决了连接的问题,又碰到另一个问题就是:已经查找到数据了,在将数据放到response中返回时,前台接收不到返回值...本人新手还望大佬不吝赐教,感谢
![image](https://user-images.githubusercontent.com/32890926/55677603-7eee9780-591d-11e9-90a6-7ed1600bf61e.png)
![image](https://user-images.githubusercontent.com/32890926/55677615-93329480-591d-11e9-9e4c-f0d5ef4ce0d2.png)
![image](https://user-images.githubusercontent.com/32890926/55677629-f3c1d180-591d-11e9-949a-89524e6e6789.png)

**Comment by Molunerfinn** [comment]
你这个可能是某些中间件做了某些拦截，使得返回的结果变成了`Not Found`.

**Comment by Molunerfinn** [comment]
或者就是你某些中间件写了`next()`，但是由于那个中间件是异步操作，所以直接返回`Not Found`了。正确做法是在需要异步操作的中间件里的`next()`前面加个`await next()`，并且next之前的异步操作也换成`await`的形式。

**Comment by Essentric** [comment]
哇,感谢大佬的分析,一语中的
