### ISSUE TITLE
前端无法引用后端模块jsonwebtoke

### ISSUE THREAD

**Issue by shawli123** [Molunerfinn/vue-koa-demo#5]
你好，我在vue组件中引入jsonwebtoken模块时，报错如下：

 ERROR  Failed to compile with 2 errors                                                                         22:10:55

These dependencies were not found:

* net in ./~/joi/lib/string.js
* dns in ./~/isemail/lib/isemail.js

To install them, you can run: npm install --save net dns
> Listening at http://localhost:8080

这个要怎么解决，按它的提示安装额外的后端模块也不奏效。。

**Comment by Molunerfinn** [comment]
这个[issue](https://github.com/hapijs/joi/issues/665#issuecomment-113713020)可以参考，我把koa1的分支的这个问题修复了，koa2版本的一开始我就改过啦:)
