### ISSUE TITLE
项目跑起来了，但是登录接口报504，登录不了 。

### ISSUE THREAD

**Issue by oo10** [Molunerfinn/vue-koa-demo#8]
$ npm run dev

> vue-koa-demo@1.0.0 dev C:\Users\Administrator\Desktop\2017.6\vue-koa-demo
> node build/dev-server.js

[HPM] Proxy created: /auth  ->  http://localhost:8889
[HPM] Proxy created: /api  ->  http://localhost:8889
> Starting dev server...
 DONE  Compiled successfully in 8258ms12:41:49

> Listening at http://localhost:8080

**[HPM] Error occurred while trying to proxy request /auth/user from localhost:8080 to http://localhost:8889 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)**

配置了自己的mysql密码，这是什么原因导致的呢。

**Comment by cgygd** [comment]
你好。我也遇到这个问题，请问你怎么解决的？

**Comment by wenhui-huang** [comment]
我也是，请问你们是怎么解决的 @cgygd @oo10

**Comment by YuFengDing** [comment]
你们解决了吗 - -

**Comment by Molunerfinn** [comment]
@YuFengDing 你的`.env`文件长什么样？

**Comment by YuFengDing** [comment]
# your database username
DB_USER=root
# your database
DB_PASSWORD='' 
# Koa is listening to this port
PORT=8889

**Comment by Molunerfinn** [comment]
@YuFengDing 
如果是在windows下运行的话，需要分开运行前端和后端：
```bash
npm run dev
```
然后在另一个窗口运行
```bash
npm run server
````
分开查看两个窗口的报错信息。如果run server的后端报`ECONNREFUSED`的错误一般是你的8889端口被占用了。要么换一个端口要么杀掉之前8889端口的进程。然后重新跑一遍`npm run server`

**Comment by YuFengDing** [comment]
@Molunerfinn 我把两个端口前台和后台都换了 但是请求的时候现在爆出 500

**Comment by Molunerfinn** [comment]
@YuFengDing 改了后端的端口的话你需要把proxyTable里的端口也换成跟Koa的端口一致：
https://github.com/Molunerfinn/vue-koa-demo/blob/master/config/index.js
![image](https://user-images.githubusercontent.com/12621342/38670245-d07c831e-3e7a-11e8-9edd-fe47a84b7de5.png)
如果都换了还是有报错注意看后端的报错信息，看看是啥报错

**Comment by YuFengDing** [comment]
@Molunerfinn 看到具体报错了 
![image](https://user-images.githubusercontent.com/23763023/38672326-6e45ad14-3e80-11e8-9c14-14c08dae2f54.png) 貌似是db连接问题 我在看一下  感谢指导
